### ISSUE TITLE
datacarpentry/openrefine-socialsci

### ISSUE THREAD

**Issue by zkamvar** [carpentries/lesson-transition#49]
tracking issues for <https://github.com/datacarpentry/openrefine-socialsci>/

- [x] link issues 
  ```markdown
  index.md:34 [missing file]: [Setup](setup.html)
  index.md:53 [missing file]: [Instructor notes](guide/)
  ```
- [x] fix callout in setup list (note: this is likely similar to the setup callout issues in #46)
- [x] fix first title appearing above questions/objectives (fixed in https://github.com/carpentries/pegboard/pull/124)
- [x] fix setup instructions (this may have been fixed with https://github.com/carpentries/pegboard/issues/120), but I need to find the correct place for these links
- [x] investigate encroachig solution in callout block (for maintainers to address how they want to do this either via https://github.com/carpentries/lesson-transition/issues/46#issuecomment-1522014660 or by transforming point 6 into a callout under point 5 and appending the solution)

**Comment by bencomp** [comment]
First: thanks for your efforts!
Looking at the preview in Firefox for Android, I notice a few things.

![Screenshot_20230414-233036_Firefox.jpg](https://user-images.githubusercontent.com/1303898/232158728-1a8f577c-5d69-4f77-baf8-9d1335c5b68c.jpg)

![Screenshot_20230414-233042_Firefox.jpg](https://user-images.githubusercontent.com/1303898/232158898-584fa6fc-d432-4d39-a159-5d74a8a5a0c3.jpg)

Callouts are not (always?) translated into new style callouts.

![Screenshot_20230414-232940_Firefox.jpg](https://user-images.githubusercontent.com/1303898/232158991-a81f7a96-1c8b-4bb7-a9d4-6cb5d2ef3c40.jpg)

First section title appears above objectives.

![Screenshot_20230414-232932_Firefox.jpg](https://user-images.githubusercontent.com/1303898/232159121-bef8e597-a356-4cb3-894b-a1b25cc0420d.jpg)

Space between two inline preformatted strings is invisible (or removed, I cannot tell on mobile).

![Screenshot_20230414-232918_Firefox.jpg](https://user-images.githubusercontent.com/1303898/232159322-5240a4c9-00cf-4489-b882-5a8c96d926e0.jpg)

"Show me the solution" partially obscures body text.

**Comment by bencomp** [comment]
Hi @zkamvar, thanks for fixing the issues and commenting. I did indeed notice that some things looked better already :)

I think the encroaching block is also related to #datacarpentry/openrefine-socialsci#121 – as we have a solution without corresponding exercise. I will have a look at transforming the whole thing into exercise+solution, or following your solution.

**Comment by zkamvar** [comment]
That's great! I will comment within the next hour about the transition once I run my tests.

**Comment by zkamvar** [comment]
fixed in a36c90ea88fd46dd10bed7bcfc116e1678bef116
